### ISSUE TITLE
support scripted transactions

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/threefold-wallet-electron#202]
It would be cool to support a tab in transactions where power users can make a transaction based on more complicated logic, some examples:

- send money to a user, locked over several timestamps;
- pay out several users at once, optionally with arbitrary data and timelocks;

I would keep it simple for now, and just put a big text field where the script can be pasted with a button execute.

Global variables we would expose:

- wallets
- balance
- chain = { height | timestamp }
- date functionality
- functional-like features (map, filter, ...)

**Comment by GlenDC** [comment]
LISP seems ideal for this purpose, we could see if libraries such as <https://github.com/maryrosecook/littlelisp> can help.

**Comment by GlenDC** [comment]
Supported now, using safe-eval from NPM.

**Comment by robvanmieghem** [comment]
@GlenDC Can you add a link to the commit or pr?

**Comment by GlenDC** [comment]
Sure, you can pretty much all of it at https://github.com/threefoldtech/threefold-wallet-electron/pull/284.

For now only `Currency` (the type) and the selected wallet object `wallet` .

It works good enough, can be extended if needed (but probably not required). This allows peter to also execute the more complex transfers that need to happen for certain payments (see the example in the README for example).
