### ISSUE TITLE
ensure user wallets created with older versions are automatically migrated to new storage directory

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/threefold-wallet-electron#221]
As we rename the application from `tfchain-wallet` to `threefold-wallet` we'll have a new root FS dir for our stored wallets. This is OK, but we should at startup also quickly check if there are wallets still in old directory space that we don't know yet, and if so, add those automatically to the new space. Such that existing users will be able to keep using their existing wallets with the new wallet application.

**Comment by GlenDC** [comment]
blocked by #158.

**Comment by DylanVerstraete** [comment]
closed in https://github.com/threefoldtech/threefold-wallet-electron/commit/acc201cadf7bda4a9092171ae59fd666913a58c2
