### ISSUE TITLE
support gold coin burn transaction (4th tab in send page) in frontend

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/threefold-wallet-electron#240]
Blocked by <https://github.com/threefoldtech/threefold-wallet-electron/issues/239>, the backend issue has to be finished first.

**Comment by GlenDC** [comment]
Functional design I have in mind (please do style it better than my fast mockup):

<img width="848" alt="Screenshot 2019-07-30 at 16 10 53" src="https://user-images.githubusercontent.com/3900482/62146317-6e5f9400-b2f5-11e9-90a7-deb1891ff541.png">
<img width="848" alt="Screenshot 2019-07-30 at 16 10 53 copy" src="https://user-images.githubusercontent.com/3900482/62146318-6ef82a80-b2f5-11e9-9705-2683bade5468.png">

As you can see it will be a new transaction tab, available in the `send` page as "burn transaction".

User has to define an amount, optionally the user can switch wallet (as always, to fund from), and a message.

Structured messages are now possible too. So you'll need to define a message type radio button list, so the user can choose between "free formatted" message or a "structured" message. For burn transaction I would put the default type on "structured message", as it makes the most sense for this type of transaction, given you are burning in order to convert your tokens.

When the "free formatted" message option is selected, the user can type in an optional message, as was already possible on other transaction tabs (NOTE: please name it message instead of description, makes more sense IMHO).

When the "structured message" option is selected, the user gets 3 different fields (similar to what you are used to in bank online transfers, at least for Belgian banks). Please make sure that the field automatically jumps from one field to another while you type (meaning if you finished typing in the first of three fields, as in that field is full, it should jump to the next, and than afterwards when that one is full to the third and last field.

For validation of the 3 structured message fields it goes as follows:

- all fields can only represent numeric characters (so `0`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8` and  `9`);
- the first field can maximum contain 3 characters
- the second field can maximum contain 4 characters
- the third field can maximum contain 5 characters

Sending a coin transfer can be done using the API, e.g. to burn 100 coins:
```javascript
msg = 'this is a free format message'
msg = [123, 4567, 89012] // example of a structured message
msg = ['123', '4567', '89012'] // also an example of a structured message
wallet.coins_burn('100', {message: msg}) // returns a promise in the same format as you are used to
```

As you can see the structured message can be both a list of strings as well a list integers.

**Comment by DylanVerstraete** [comment]
Blocked on parsing the structured message in the transaction list after you burn tokens providing a structured message. 

<img width="921" alt="Schermafbeelding 2019-08-13 om 10 02 29" src="https://user-images.githubusercontent.com/17138347/62924941-803f3d80-bdb1-11e9-951d-555be19593f2.png">

**Comment by DylanVerstraete** [comment]
Closed by https://github.com/threefoldtech/threefold-wallet-electron/commit/816c10f7cdeb16f4d914214e0f1ce55d3d199bfd
