### ISSUE TITLE
after deleting all accounts, lock files are generated in storage and still show account on homepage

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/threefold-wallet-electron#97]
path `/Users/dylan/Library/Application\ Support/Electron/storage/tfchain`

**Comment by GlenDC** [comment]
How did you delete all files @DylanVerstraete? I think if you deleted the accounts by directly deleting the files on the FS, while the App is still running, then this might be the issue. I think the storage module keeps a lock file while running. If not, how did you delete all accounts?

**Comment by DylanVerstraete** [comment]
Created an issue https://github.com/electron-userland/electron-json-storage/issues/132 on the repo that we use for storage. I'm further investigating if this may be an issue on our side. The problem is that they don't provide like an update function.

Right now, when saving an account, we delete the file on disk (which has a name equal to the account name) and then we create a new file with the new name (so we can later get the data). Maybe this approach is wrong. I don't see any api methods that allow us to modify the contents of the file and also rename it (to the new account name).

**Comment by GlenDC** [comment]
Moved to next milestone. It doesn't happen often. If it does happen it is fairly harmless, though annoying.

**Comment by DylanVerstraete** [comment]
Should be closed by [https://github.com/electron-userland/electron-json-storage/pull/137](https://github.com/electron-userland/electron-json-storage/pull/137)
